### ISSUE TITLE
Unable to resolve type of columns in a view

### ISSUE THREAD

**Issue by theianrobertson** [Teradata/sqlalchemy-teradata#27]
Trying to [reflect a view](http://docs.sqlalchemy.org/en/latest/core/reflection.html#reflecting-views), and I'm getting an error when it's trying to resolve types:

```python
from sqlalchemy import (Table, MetaData, create_engine)

conn_string = 'teradata://user:pass@host:22/'
engine = create_engine(conn_string)
metadata = MetaData(engine)
my_table = Table(
    'view_name', metadata, autoload=True, autoload_with=engine, schema='some_db')
```

Raises

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 439, in __new__
    metadata._remove_table(name, schema)
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 434, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 514, in _init
    include_columns, _extend_on=_extend_on)
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 527, in _autoload
    _extend_on=_extend_on
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2045, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1534, in run_callable
    return callable_(self, *args, **kwargs)
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 372, in reflecttable
    table, include_columns, exclude_columns, **opts)
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 598, in reflecttable
    table_name, schema, **table.dialect_kwargs):
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 369, in get_columns
    **kw)
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy_teradata/dialect.py", line 183, in get_columns
    return [self._get_column_info(row) for row in res]
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy_teradata/dialect.py", line 183, in <listcomp>
    return [self._get_column_info(row) for row in res]
  File "/Users/me/miniconda3/envs/sqlalch/lib/python3.6/site-packages/sqlalchemy_teradata/dialect.py", line 149, in _get_column_info
    length=int(row['columnlength']),\
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

As far as I can tell it's due to using `dbc.ColumnsV` in `dialect.get_columns` ([here](https://github.com/Teradata/sqlalchemy-teradata/blob/master/sqlalchemy_teradata/dialect.py#L168)) - views don't populate `columnname`, `columntype`, etc. (or at least my views don't 😁 ).  Will try to tool around with `type(some_db.view_name.column_name)` and see if I can get something working, unless anyone has any other good ideas!

**Comment by devonyates** [comment]
Hi, I'm running into the same problem.  Sounds like you have a good idea how to solve it.  Let me know how it's going, and if you need a hand.

**Comment by RemiTurpaud** [comment]
From TD 16, view data types/length can be queried from `dbc.columnsQV`. This should be relatively simple to update the `dialect.get_columns()` function with this.

For earlier versions, the `help column` statement may be more appropriate than `type()` (that would require select rights, at least a row of data, etc...). However, this would still add a considerable overhead (we would issue a statement for every column). 
A simple workaround could be to default the view column types to the least restrictive type for SQLAlchemy (I would say VARCHAR, not sure if SQLA has something more generic). This is a bit of a hack, but at least the reflection will not fail and the views could be selected.
